apiVersion: v1
kind: Service
metadata:
  name: production-cicd-service
spec:
  type: NodePort
  selector:
    app: production-cicd-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081
